# .github/workflows/main.yml

name: "Typical Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: configure
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Run debug log
      uses: ./.github/actions/test
    - name: Run tests
      run: ${{github.workspace}}/build/unit_test
    - name: Application test run
      run: ${{github.workspace}}/build/hello_cmake
