# .github/workflows/main.yml

name: "Typical Workflow"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: configure
      run: cmake -B ${{github.workspace}}/build
    - name: domake
      run: cmake --build ${{github.workspace}}/build
    - name: Run debug log
      uses: ./.github/actions/test
    - name: Unit test run
      run: ${{github.workspace}}/build/hello_cmake
    - name: Run app
      run: ${{github.workspace}}/build/unit_tests
    - name: Add success comment to PR
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          gh pr comment ${{ github.event.number }} --body "Job success"
        else
          gh pr comment ${{ github.event.number }} --body "Job fail!"
        fi

